title: Hi there 👋, I'm Exneyder A. Montoya-Araque
description:
logo: /images/eama.png
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
