title: Hi there 👋, I'm Exneyder A. Montoya-Araque
description: Personal website
logo: /images/eama.png
show_downloads: false
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
